Vagrant.configure("2") do |config|
  config.vm.define "kub" do |kub|

    kub.vm.provider "vmware_desktop" do |vm_kub|
      vm_kub.gui = false
      vm_kub.vmx['numvcpus'] = '8' 
      vm_kub.vmx['memsize'] = '24576'
      vm_kub.ssh_info_public = true
    end


    kub.vm.box = "generic/ubuntu2204"
    kub.vm.hostname = "k8s-masternode"
    kub.vm.synced_folder "../data", "/vagrant_data"
=begin
    kub.vm.network "forwarded_port", guest: 8001, host: 8001
=end

    kub.vm.provision "shell", path: "setup.sh"
    kub.vm.provision "shell", path: "kubernetes - setup.sh"
    kub.vm.provision "shell", path: "kong.sh"
    kub.vm.provision "shell", path: "harbor.sh"
    kub.vm.provision "shell", path: "prometheus.sh"
    kub.vm.provision "shell", path: "dashboard.sh"
=begin
    kub.vm.provision "shell", path: "otel.sh"
=end

    kub.vm.provision "shell", inline: <<-SHELL
		export DEBIAN_FRONTEND=noninteractive

# containerd
    # https://devopscube.com/setup-grafana-kubernetes/
		#sudo kubectl apply -f /vagrant_data/kubernetes/grafana/grafana-datasource-config.yaml
		#sudo kubectl apply -f /vagrant_data/kubernetes/grafana/deployment.yaml
		#sudo kubectl apply -f /vagrant_data/kubernetes/grafana/service.yaml

    SHELL

  end
end