# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.define "kub" do |kub|

    kub.vm.provider "vmware_desktop" do |vm_kub|
      vm_kub.gui = true
      vm_kub.vmx['numvcpus'] = '2' 
      vm_kub.vmx['memsize'] = '4096'
    end

    kub.vm.provider "virtualbox" do |vb_kub|
      vb_kub.gui = true
      vb_kub.memory = 4096
      vb_kub.cpus = 2
      vb_kub.customize ["modifyvm", :id, "--vram", "32"]
    end

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    kub.vm.box = "rockylinux/9"
    kub.vm.hostname = "kubernetes-vm"
    # kub.vm.network "private_network", ip: "192.168.91.200"
    kub.vm.synced_folder "../data", "/vagrant_data"
    kub.vm.network "forwarded_port", guest: 8001, host: 8001
    kub.vm.network "forwarded_port", guest: 6443, host: 6443
    kub.vm.network "forwarded_port", guest: 30000, host: 30000
    kub.vm.network "forwarded_port", guest: 30001, host: 30001
    kub.vm.network "forwarded_port", guest: 30002, host: 30002
    kub.vm.network "forwarded_port", guest: 30003, host: 30003
    kub.vm.network "forwarded_port", guest: 30004, host: 30004
=begin
    # Expose NodePort ports
    for p in 30000..30100
      kub.vm.network "forwarded_port", guest: p, host: p, protocol: "tcp"
    end
=end
    # Disable automatic box update checking. If you disable this, then
    # boxes will only be checked for updates when the user runs
    # `vagrant box outdated`. This is not recommended.
    # config.vm.box_check_update = false

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # NOTE: This will enable public access to the opened port
    # config.vm.network "forwarded_port", guest: 80, host: 8080

    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine and only allow access
    # via 127.0.0.1 to disable public access
    # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # config.vm.network "private_network", ip: "192.168.33.10"

    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    # config.vm.network "public_network"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # config.vm.synced_folder "../data", "/vagrant_data"

    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    # config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    #   vb.memory = "1024"
    # end
    #
    # View the documentation for the provider you are using for more
    # information on available options.
=begin
    kub.vm.provision :k3s, run: "once" do |k3s|
      # installer_url: can be anything that curl can access from the guest
      # default =>`https://get.k3s.io`
      # type => String
      k3s.installer_url = 'https://get.k3s.io'

      # args: are command line arguments to be passed to the shell, e.g.:
      # `curl ... | sh -s - #{args}`
      # type => String || Array<string>
      k3s.args = "server --selinux"
      # or
      k3s.args = %w[server --selinux]

      # env: environment variables to be set before invoking the installer script
      # type => String || Array<String> || Hash
      k3s.env = %w[K3S_KUBECONFIG_MODE=0644 K3S_TOKEN=vagrant]
      # or
      k3s.env = ENV.select{|k| k.start_with?('K3S_') || k.start_with?('INSTALL_K3S_')}.merge({
        :K3S_KUBECONFIG_MODE => '0640', # pass this as a string unless you like weird results in your guest ...
        :K3S_SELINUX => true,
      })
      # or
      k3s.env = <<~ENV
        K3S_KUBECONFIG_MODE=0640
        K3S_SELINUX=true
      ENV

      # env_path: where to write the envvars to be sourced prior to invoking the installer script
      # default => `/etc/rancher/k3s/install.env`
      k3s.env_path = '/etc/rancher/k3s/install.env'
      k3s.env_mode = '0600' # default
      k3s.env_owner = 'root:root' #default

      # config: config file content in yaml
      # type => String || Hash
      k3s.config = {
        :disable => %w[local-storage servicelb]
      }
      # or
      k3s.config = <<~YAML
        disable:
        - local-storage
        - servicelb
      YAML
      # config_mode: config file permissions
      # type => String
      # default => `0600`
      k3s.config_mode = '0644' # side-step https://github.com/k3s-io/k3s/issues/4321
      k3s.config_owner = 'root:root' #default

      # config_path: where to write the config yaml.
      # if you override this be sure to let k3s know, e.g.
      #   k3s.env = { :INSTALL_K3S_EXEC => '--config=/some/other/config.yaml' }
      # or
      #   k3s.args = '--config=/some/other/config.yaml'
      # default => `/etc/rancher/k3s/config.yaml`
      k3s.config_path = '/etc/rancher/k3s/config.yaml'

      # skip_start: install but don't start K3s
      # type => Boolean
      # default => false
      # k3s.skip_start = true
    end
=end

    kub.vm.provision "shell", inline: <<-SHELL
      dnf install epel-release -y
      dnf update --refresh -y
      dnf install dkms kernel-devel kernel-headers gcc make bzip2 perl elfutils-libelf-devel -y
    SHELL

    kub.vm.provision :reload

    kub.vm.provision "shell", inline: <<-SHELL
      curl --progress-bar --remote-name https://download.virtualbox.org/virtualbox/7.0.4/VBoxGuestAdditions_7.0.4.iso
      mv VBoxGuestAdditions_7.0.4.iso /tmp/
      sudo mount /tmp/VBoxGuestAdditions_7.0.4.iso /run/media/
      dnf install libX11 libXt libXext libXmu -y
      sudo /run/media/VBoxLinuxAdditions.run
      echo "VirtualBox additions updated"
    SHELL

    kub.vm.provision :reload

    kub.vm.provision "shell", inline: <<-SHELL
      # dnf update -y
      dnf install mc wget net-tools -y -q

      # https://levelup.gitconnected.com/local-kubernetes-development-using-vagrant-and-k3s-547bd5687a7f
      echo "Installing k3s"
      curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -
      echo "k3s installed"

      echo "Creating admin user"
      # https://docs.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengaddingserviceaccttoken.htm

      #/usr/local/bin/kubectl -n kube-system create serviceaccount ls-account
      #/usr/local/bin/kubectl -n kube-system create rolebinding ls-account-rolebinding --clusterrole=cluster-admin --serviceaccount=kube-system:ls-account
      /usr/local/bin/kubectl apply -f /vagrant_data/kubernetes/dashboard/admin-user.yaml
      #/usr/local/bin/kubectl describe secrets oke-ls-account-token -n kube-system
      /usr/local/bin/kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')

      echo "Installing Dashboard"
      /usr/local/bin/kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
      /usr/local/bin/kubectl apply -f /vagrant_data/kubernetes/dashboard/dashboard-service.yaml


      # https://0to1.nl/post/k3s-kubectl-permission/
      #sudo chmod 644 /etc/rancher/k3s/k3s.yaml
	    #echo K3S_KUBECNFIG_MODE=\"644\" >> /etc/systemd/system/k3s.service.env
      
      #sudo mkdir ~/.kube
      #sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config 
      #sudo chown $USER ~/.kube/config 
      #sudo chmod 600 ~/.kube/config
      #export KUBECONFIG=~/.kube/config

      echo "Installing Prometheus"
      /usr/local/bin/kubectl create namespace monitoring
      /usr/local/bin/kubectl create -f /vagrant_data/kubernetes/prometheus/clusterRole.yaml
      /usr/local/bin/kubectl create -f /vagrant_data/kubernetes/prometheus/config-map.yaml
      /usr/local/bin/kubectl create -f /vagrant_data/kubernetes/prometheus/prometheus-deployment.yaml
      echo "Waiting deployment is finished"
      /usr/local/bin/kubectl wait deployment -n monitoring prometheus-deployment --for condition=Available=True --timeout=120s
      /usr/local/bin/kubectl get deployments --namespace=monitoring
      /usr/local/bin/kubectl get pods --namespace=monitoring
      echo "Prometheus installed"

      /usr/local/bin/kubectl get all --all-namespaces
      /usr/local/bin/kubectl cluster-info

      /usr/local/bin/kubectl create -f /vagrant_data/kubernetes/prometheus/prometheus-service.yaml --namespace=monitoring
      /usr/local/bin/kubectl get services -n monitoring

      /usr/local/bin/kubectl apply -f https://k8s.io/examples/controllers/nginx-deployment.yaml
      /usr/local/bin/kubectl wait deployment nginx-deployment --for condition=Available=True --timeout=120s
      /usr/local/bin/kubectl apply -f /vagrant_data/kubernetes/nginx-sample/nginx-service.yaml



    SHELL

  end
  
  config.vm.define "es" do |elasticsearch|
    elasticsearch.vm.provider "vmware_desktop" do |vm_es|
      vm_es.gui = false
      vm_es.vmx['numvcpus'] = '2' 
      vm_es.vmx['memsize'] = '3072'
    end

    elasticsearch.vm.box = "rockylinux/9"
    elasticsearch.vm.hostname = "elasticsearch-vm"
    elasticsearch.vm.network "private_network", ip: "192.168.91.100"
    elasticsearch.vm.synced_folder "../data", "/vagrant_data"
    elasticsearch.vm.network "forwarded_port", guest: 9200, host: 9200
    elasticsearch.vm.network "forwarded_port", guest: 9300, host: 9300

    elasticsearch.vm.provision "shell", inline: <<-SHELL
      dnf install wget mc net-tools -y -q
      # dnf update -y
	  
      curl --progress-bar --remote-name --location https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.5.3-x86_64.rpm
      curl --progress-bar --remote-name --location https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.5.3-x86_64.rpm.sha512
      sha512sum -c elasticsearch-8.5.3-x86_64.rpm.sha512 
      sudo rpm --install elasticsearch-8.5.3-x86_64.rpm

      sudo cp /vagrant_data/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
      sudo systemctl daemon-reload
      sudo systemctl enable elasticsearch.service
      sudo systemctl start elasticsearch.service

      sudo /usr/share/elasticsearch/bin/elasticsearch-reset-password -a -b -s -u elastic > /vagrant_data/elasticsearch-password
      
      sudo /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana > /vagrant_data/kibana-enrollment
    SHELL
	
  end

  config.vm.define "kibana" do |kibana|
    kibana.vm.provider "vmware_desktop" do |vm_kib|
      vm_kib.gui = false
      vm_kib.vmx['numvcpus'] = '2' 
      vm_kib.vmx['memsize'] = '3072'
    end

    kibana.vm.box = "rockylinux/9"
    kibana.vm.hostname = "kibana-vm"
    kibana.vm.network "private_network", ip: "192.168.91.101"
    kibana.vm.synced_folder "../data", "/vagrant_data"
    kibana.vm.network "forwarded_port", guest: 5601, host: 5601

    kibana.vm.provision "shell", inline: <<-SHELL
      dnf install wget mc vim net-tools -y -q
      # dnf update -y

      sudo update-crypto-policies --set DEFAULT:SHA1
      sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

      sudo cat <<EOT >> /etc/yum.repos.d/kibana.repo
[kibana-8.x]
name=Kibana repository for 8.x packages
baseurl=https://artifacts.elastic.co/packages/8.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md
EOT

      sudo dnf install -y kibana
    
      sudo cp /vagrant_data/kibana.yml /etc/kibana/kibana.yml

      es_enroll=$(cat /vagrant_data/kibana-enrollment)
      sudo /usr/share/kibana/bin/kibana-setup --enrollment-token $es_enroll

      sudo systemctl daemon-reload
      sudo systemctl enable kibana.service
      sudo systemctl start kibana.service
    SHELL
  end
end